version: '3.8'

services:
  kids-reading-manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: kids-reading-manager:latest
    container_name: kids-reading-manager
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge