version: '3.8'

services:
  # Frontend service
  kids-reading-manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: kids-reading-manager:latest
    container_name: kids-reading-manager
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - api-server

  # Backend API server
  api-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: kids-reading-manager-api:latest
    container_name: kids-reading-manager-api
    restart: unless-stopped
    environment:
      - PORT=3001
      - DATA_FILE=/data/students.json
    volumes:
      - reading-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  reading-data:
    driver: local