import { Hono } from 'hono';
import { generateId } from '../utils/helpers';

// Import services (legacy KV mode)
import {
  getClasses as getClassesKV,
  getClassById as getClassByIdKV,
  saveClass as saveClassKV,
  deleteClass as deleteClassKV
} from '../services/kvService';

// Import utilities
import { notFoundError, badRequestError, forbiddenError } from '../middleware/errorHandler';
import { auditLog, requireReadonly, requireTeacher } from '../middleware/tenant';
import { permissions } from '../utils/crypto';
import { getDB, isMultiTenantMode } from '../utils/routeHelpers';
import { validateClass } from '../utils/validation';
import { rowToClass, rowToStudent, rowToClassGoal } from '../utils/rowMappers';
import { resolveCurrentTerm, getAutoGeneratedTargets } from '../utils/classGoalsEngine.js';


// Create router
const classesRouter = new Hono();

/**
 * GET /api/classes
 * Get all classes
 */
classesRouter.get('/', requireReadonly(), async (c) => {
  // Multi-tenant mode: use D1
  if (isMultiTenantMode(c)) {
    const db = getDB(c.env);
    const organizationId = c.get('organizationId');
    
    const result = await db.prepare(`
      SELECT c.*, COUNT(s.id) as student_count
      FROM classes c
      LEFT JOIN students s ON s.class_id = c.id AND s.is_active = 1
      WHERE c.organization_id = ? AND c.is_active = 1
      GROUP BY c.id
      ORDER BY c.name ASC
    `).bind(organizationId).all();
    
    const classes = (result.results || []).map(row => ({
      ...rowToClass(row),
      studentCount: row.student_count
    }));
    
    return c.json(classes);
  }
  
  // Legacy mode: use KV
  const classes = await getClassesKV(c.env);
  return c.json(classes);
});

/**
 * GET /api/classes/:id
 * Get a class by ID
 */
classesRouter.get('/:id', requireReadonly(), async (c) => {
  const { id } = c.req.param();
  
  // Multi-tenant mode: use D1
  if (isMultiTenantMode(c)) {
    const db = getDB(c.env);
    const organizationId = c.get('organizationId');
    
    const cls = await db.prepare(`
      SELECT c.*, 
        (SELECT COUNT(*) FROM students s WHERE s.class_id = c.id AND s.is_active = 1) as student_count
      FROM classes c
      WHERE c.id = ? AND c.organization_id = ? AND c.is_active = 1
    `).bind(id, organizationId).first();
    
    if (!cls) {
      throw notFoundError(`Class with ID ${id} not found`);
    }
    
    return c.json({
      ...rowToClass(cls),
      studentCount: cls.student_count
    });
  }
  
  // Legacy mode: use KV
  const cls = await getClassByIdKV(c.env, id);
  
  if (!cls) {
    throw notFoundError(`Class with ID ${id} not found`);
  }
  
  return c.json(cls);
});

/**
 * GET /api/classes/:id/students
 * Get all students in a class
 */
classesRouter.get('/:id/students', requireReadonly(), async (c) => {
  const { id } = c.req.param();
  
  // Multi-tenant mode: use D1
  if (isMultiTenantMode(c)) {
    const db = getDB(c.env);
    const organizationId = c.get('organizationId');
    
    // Verify class exists and belongs to organization
    const cls = await db.prepare(`
      SELECT id FROM classes WHERE id = ? AND organization_id = ? AND is_active = 1
    `).bind(id, organizationId).first();
    
    if (!cls) {
      throw notFoundError(`Class with ID ${id} not found`);
    }
    
    const result = await db.prepare(`
      SELECT * FROM students WHERE class_id = ? AND organization_id = ? AND is_active = 1 ORDER BY name ASC
    `).bind(id, organizationId).all();
    
    const students = (result.results || []).map(rowToStudent);
    
    return c.json(students);
  }
  
  // Legacy mode: not directly supported, return empty
  return c.json([]);
});

/**
 * POST /api/classes
 * Add a new class
 */
classesRouter.post('/', auditLog('create', 'class'), async (c) => {
  const body = await c.req.json();

  // Validate class data
  const validation = validateClass(body);
  if (!validation.isValid) {
    throw badRequestError(validation.errors.join('; '));
  }
  
  // Multi-tenant mode: use D1
  if (isMultiTenantMode(c)) {
    try {
      const db = getDB(c.env);
      const organizationId = c.get('organizationId');
      const userId = c.get('userId');
      
      // Check permission
      const userRole = c.get('userRole');

      if (!permissions.canManageClasses(userRole)) {
        throw forbiddenError();
      }

      const classId = generateId();
      
      await db.prepare(`
        INSERT INTO classes (id, organization_id, name, teacher_name, academic_year, created_by)
        VALUES (?, ?, ?, ?, ?, ?)
      `).bind(
        classId,
        organizationId,
        body.name,
        body.teacherName || null,
        body.academicYear || new Date().getFullYear().toString(),
        userId
      ).run();
      
      // Fetch the created class
      const cls = await db.prepare(`
        SELECT * FROM classes WHERE id = ?
      `).bind(classId).first();

      return c.json(rowToClass(cls), 201);
    } catch (error) {
      console.error('Error in POST /api/classes (multi-tenant):', error.message, error.stack);
      throw error;
    }
  }
  
  // Legacy mode: use KV
  const newClass = {
    id: body.id || generateId(),
    name: body.name,
    teacherName: body.teacherName || '',
    createdAt: body.createdAt || new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };
  
  const savedClass = await saveClassKV(c.env, newClass);
  return c.json(savedClass, 201);
});

/**
 * PUT /api/classes/:id
 * Update a class
 */
classesRouter.put('/:id', auditLog('update', 'class'), async (c) => {
  const { id } = c.req.param();
  const body = await c.req.json();

  // Validate class data
  const validation = validateClass(body);
  if (!validation.isValid) {
    throw badRequestError(validation.errors.join('; '));
  }
  
  // Multi-tenant mode: use D1
  if (isMultiTenantMode(c)) {
    const db = getDB(c.env);
    const organizationId = c.get('organizationId');
    
    // Check permission
    const userRole = c.get('userRole');
    if (!permissions.canManageClasses(userRole)) {
      throw forbiddenError();
    }

    // Check if class exists and belongs to organization
    const existing = await db.prepare(`
      SELECT id FROM classes WHERE id = ? AND organization_id = ? AND is_active = 1
    `).bind(id, organizationId).first();
    
    if (!existing) {
      throw notFoundError(`Class with ID ${id} not found`);
    }
    
    // Update class
    await db.prepare(`
      UPDATE classes SET
        name = ?,
        teacher_name = ?,
        academic_year = ?,
        disabled = ?,
        updated_at = datetime("now")
      WHERE id = ? AND organization_id = ?
    `).bind(
      body.name,
      body.teacherName || null,
      body.academicYear || null,
      body.disabled ? 1 : 0,
      id,
      organizationId
    ).run();
    
    // Fetch updated class
    const cls = await db.prepare(`
      SELECT * FROM classes WHERE id = ?
    `).bind(id).first();
    
    return c.json(rowToClass(cls));
  }
  
  // Legacy mode: use KV
  const existingClass = await getClassByIdKV(c.env, id);
  if (!existingClass) {
    throw notFoundError(`Class with ID ${id} not found`);
  }
  
  const updatedClass = {
    ...existingClass,
    name: body.name,
    teacherName: body.teacherName || existingClass.teacherName || '',
    updatedAt: new Date().toISOString()
  };
  
  const savedClass = await saveClassKV(c.env, updatedClass);
  return c.json(savedClass);
});

/**
 * DELETE /api/classes/:id
 * Delete a class (soft delete in multi-tenant mode)
 */
classesRouter.delete('/:id', auditLog('delete', 'class'), async (c) => {
  const { id } = c.req.param();
  
  // Multi-tenant mode: use D1 (soft delete)
  if (isMultiTenantMode(c)) {
    const db = getDB(c.env);
    const organizationId = c.get('organizationId');
    
    // Check permission
    const userRole = c.get('userRole');
    if (!permissions.canManageClasses(userRole)) {
      throw forbiddenError();
    }

    // Check if class exists
    const existing = await db.prepare(`
      SELECT id FROM classes WHERE id = ? AND organization_id = ? AND is_active = 1
    `).bind(id, organizationId).first();
    
    if (!existing) {
      throw notFoundError(`Class with ID ${id} not found`);
    }
    
    // Soft delete - also unassign students from this class
    await db.batch([
      db.prepare(`UPDATE classes SET is_active = 0, updated_at = datetime("now") WHERE id = ?`).bind(id),
      db.prepare(`UPDATE students SET class_id = NULL, updated_at = datetime("now") WHERE class_id = ?`).bind(id)
    ]);
    
    return c.json({ message: 'Class deleted successfully' });
  }
  
  // Legacy mode: use KV
  const success = await deleteClassKV(c.env, id);
  
  if (!success) {
    throw notFoundError(`Class with ID ${id} not found`);
  }
  
  return c.json({ message: 'Class deleted successfully' });
});

// GET /api/classes/:id/goals — get goals for current term (auto-creates defaults)
classesRouter.get('/:id/goals', requireTeacher(), async (c) => {
  const db = c.env.READING_MANAGER_DB;
  const organizationId = c.get('organizationId');
  const classId = c.req.param('id');

  // Resolve current term
  const termDatesResult = await db
    .prepare('SELECT term_name, start_date, end_date, academic_year FROM term_dates WHERE organization_id = ? ORDER BY start_date')
    .bind(organizationId)
    .all();

  const today = new Date().toISOString().split('T')[0];
  const { term } = resolveCurrentTerm(termDatesResult.results || [], today);

  // Check for existing goals
  let goalsResult = await db
    .prepare('SELECT * FROM class_goals WHERE class_id = ? AND term = ? AND organization_id = ?')
    .bind(classId, term, organizationId)
    .all();

  // Auto-create if none exist
  if (!goalsResult.results || goalsResult.results.length === 0) {
    const classSize = await db
      .prepare('SELECT COUNT(*) as count FROM students WHERE class_id = ? AND organization_id = ?')
      .bind(classId, organizationId)
      .first();

    const targets = getAutoGeneratedTargets(classSize?.count || 0);
    const inserts = Object.entries(targets).map(([metric, target]) =>
      db.prepare('INSERT INTO class_goals (id, organization_id, class_id, metric, target, current, term) VALUES (?, ?, ?, ?, ?, 0, ?)')
        .bind(generateId(), organizationId, classId, metric, target, term)
    );

    await db.batch(inserts);

    goalsResult = await db
      .prepare('SELECT * FROM class_goals WHERE class_id = ? AND term = ? AND organization_id = ?')
      .bind(classId, term, organizationId)
      .all();
  }

  const goals = (goalsResult.results || []).map(rowToClassGoal);
  const goalsCompleted = goals.filter((g) => g.achievedAt).length;
  const STAGES = ['seedling', 'sprout', 'bloom', 'full_garden'];

  return c.json({ goals, term, gardenStage: STAGES[Math.min(goalsCompleted, 3)], goalsCompleted });
});

// PUT /api/classes/:id/goals — update goal targets
classesRouter.put('/:id/goals', requireTeacher(), async (c) => {
  const db = c.env.READING_MANAGER_DB;
  const organizationId = c.get('organizationId');
  const classId = c.req.param('id');
  const { goals } = await c.req.json();

  if (!Array.isArray(goals)) {
    return c.json({ error: 'goals must be an array' }, 400);
  }

  const updates = [];
  for (const { metric, target } of goals) {
    if (!['sessions', 'genres', 'books'].includes(metric) || typeof target !== 'number' || target < 1) {
      return c.json({ error: `Invalid goal: metric=${metric}, target=${target}` }, 400);
    }
    // Clear achieved_at if target raised above current
    updates.push(
      db.prepare(`UPDATE class_goals SET target = ?, achieved_at = CASE WHEN ? > current THEN NULL ELSE achieved_at END WHERE class_id = ? AND metric = ? AND organization_id = ?`)
        .bind(target, target, classId, metric, organizationId)
    );
  }

  await db.batch(updates);

  const goalsResult = await db
    .prepare('SELECT * FROM class_goals WHERE class_id = ? AND organization_id = ?')
    .bind(classId, organizationId)
    .all();

  const updatedGoals = (goalsResult.results || []).map(rowToClassGoal);
  const goalsCompleted = updatedGoals.filter((g) => g.achievedAt).length;
  const STAGES = ['seedling', 'sprout', 'bloom', 'full_garden'];

  return c.json({ goals: updatedGoals, gardenStage: STAGES[Math.min(goalsCompleted, 3)], goalsCompleted });
});

export { classesRouter };

