/**
 * Class Goals Engine — term resolution and goal recalculation.
 *
 * resolveCurrentTerm(termDates, today) — find which term today falls in
 * getAutoGeneratedTargets(classSize) — generate default targets from class size
 * recalculateClassGoalProgress(db, classId, orgId, startDate, endDate, term) — update counters
 * updateClassGoalOnSession(db, studentId, orgId) — trigger recalc after a session save
 */

// ── Term Resolution ─────────────────────────────────────────────────────────

/**
 * Calendar quarter boundaries (1-indexed month, inclusive).
 * Q1: Jan–Mar, Q2: Apr–Jun, Q3: Jul–Sep, Q4: Oct–Dec
 */
const QUARTERS = [
  { q: 'Q1', start: '01-01', end: '03-31' },
  { q: 'Q2', start: '04-01', end: '06-30' },
  { q: 'Q3', start: '07-01', end: '09-30' },
  { q: 'Q4', start: '10-01', end: '12-31' },
];

function calendarQuarterFallback(today) {
  const year = today.slice(0, 4);
  const mmdd = today.slice(5); // MM-DD
  for (const { q, start, end } of QUARTERS) {
    if (mmdd >= start && mmdd <= end) {
      return {
        term: `${q} ${year}`,
        startDate: `${year}-${start}`,
        endDate: `${year}-${end}`,
      };
    }
  }
  // Fallback safety: should never reach here with valid YYYY-MM-DD
  return { term: `Q4 ${year}`, startDate: `${year}-10-01`, endDate: `${year}-12-31` };
}

/**
 * Resolve the current term from an array of term_dates rows.
 *
 * @param {Array<{term_name: string, start_date: string, end_date: string, academic_year: string}>} termDates
 * @param {string} today - YYYY-MM-DD
 * @returns {{ term: string, startDate: string, endDate: string }}
 */
export function resolveCurrentTerm(termDates, today) {
  if (Array.isArray(termDates)) {
    for (const row of termDates) {
      if (today >= row.start_date && today <= row.end_date) {
        return {
          term: `${row.term_name} ${row.academic_year}`,
          startDate: row.start_date,
          endDate: row.end_date,
        };
      }
    }
  }
  return calendarQuarterFallback(today);
}

// ── Auto-Generated Targets ───────────────────────────────────────────────────

/**
 * Generate default goal targets from class size.
 *
 * @param {number} classSize
 * @returns {{ sessions: number, genres: number, books: number }}
 */
export function getAutoGeneratedTargets(classSize) {
  return {
    sessions: classSize * 20,
    genres: 10,
    books: classSize * 4,
  };
}

// ── Progress Recalculation ───────────────────────────────────────────────────

/**
 * Recalculate class goal progress by querying session, book, and genre counts,
 * then batch-updating the class_goals rows.
 *
 * @param {object} db - D1 database binding
 * @param {string} classId
 * @param {string} orgId
 * @param {string} startDate - YYYY-MM-DD (inclusive)
 * @param {string} endDate - YYYY-MM-DD (inclusive)
 * @param {string} term - term label (e.g. 'Spring 1 2025/26')
 */
export async function recalculateClassGoalProgress(db, classId, orgId, startDate, endDate, term) {
  // 1. Fetch existing goals for this class + term
  const goalsResult = await db
    .prepare(
      `SELECT id, metric, target, current, achieved_at
       FROM class_goals
       WHERE class_id = ? AND organization_id = ? AND term = ?`
    )
    .bind(classId, orgId, term)
    .all();

  const goals = goalsResult.results || [];
  if (goals.length === 0) return;

  // 2. Count real sessions (excluding marker sessions)
  const sessionRow = await db
    .prepare(
      `SELECT COUNT(DISTINCT rs.id) AS count
       FROM reading_sessions rs
       JOIN students s ON rs.student_id = s.id
       WHERE s.class_id = ?
         AND s.organization_id = ?
         AND rs.session_date >= ?
         AND rs.session_date <= ?
         AND (rs.notes NOT LIKE '%[ABSENT]%')
         AND (rs.notes NOT LIKE '%[NO_RECORD]%')`
    )
    .bind(classId, orgId, startDate, endDate)
    .first();
  const sessionCount = sessionRow ? sessionRow.count : 0;

  // 3. Count distinct books read
  const bookRow = await db
    .prepare(
      `SELECT COUNT(DISTINCT rs.book_id) AS count
       FROM reading_sessions rs
       JOIN students s ON rs.student_id = s.id
       WHERE s.class_id = ?
         AND s.organization_id = ?
         AND rs.session_date >= ?
         AND rs.session_date <= ?
         AND rs.book_id IS NOT NULL
         AND (rs.notes NOT LIKE '%[ABSENT]%')
         AND (rs.notes NOT LIKE '%[NO_RECORD]%')`
    )
    .bind(classId, orgId, startDate, endDate)
    .first();
  const bookCount = bookRow ? bookRow.count : 0;

  // 4. Count distinct genres read (via json_each on books.genre_ids)
  const genreRow = await db
    .prepare(
      `SELECT COUNT(DISTINCT je.value) AS count
       FROM reading_sessions rs
       JOIN students s ON rs.student_id = s.id
       JOIN books b ON rs.book_id = b.id
       JOIN json_each(b.genre_ids) je
       WHERE s.class_id = ?
         AND s.organization_id = ?
         AND rs.session_date >= ?
         AND rs.session_date <= ?
         AND b.genre_ids IS NOT NULL
         AND (rs.notes NOT LIKE '%[ABSENT]%')
         AND (rs.notes NOT LIKE '%[NO_RECORD]%')`
    )
    .bind(classId, orgId, startDate, endDate)
    .first();
  const genreCount = genreRow ? genreRow.count : 0;

  const countsByMetric = {
    sessions: sessionCount,
    books: bookCount,
    genres: genreCount,
  };

  const now = new Date().toISOString();

  // 5. Build UPDATE statements for each goal
  const updateStatements = goals.map((goal) => {
    const newCurrent = countsByMetric[goal.metric] ?? goal.current;
    // Set achieved_at only when newly crossing the threshold
    let newAchievedAt = goal.achieved_at;
    if (newCurrent >= goal.target && goal.achieved_at === null) {
      newAchievedAt = now;
    }
    return db
      .prepare(`UPDATE class_goals SET current = ?, achieved_at = ? WHERE id = ?`)
      .bind(newCurrent, newAchievedAt, goal.id);
  });

  // 6. Batch all updates
  await db.batch(updateStatements);
}

// ── Session-triggered Update ─────────────────────────────────────────────────

/**
 * Called after a reading session is saved/deleted. Resolves the student's class,
 * finds the current term, and recalculates all goal progress for that class.
 * Returns newly-completed goals (those that crossed the threshold this call).
 *
 * @param {object} db - D1 database binding
 * @param {string} studentId
 * @param {string} orgId
 * @returns {Promise<Array<{metric: string, target: number, current: number}>>}
 */
export async function updateClassGoalOnSession(db, studentId, orgId) {
  // 1. Get student's class_id
  const studentRow = await db
    .prepare(`SELECT class_id FROM students WHERE id = ? AND organization_id = ?`)
    .bind(studentId, orgId)
    .first();

  if (!studentRow || !studentRow.class_id) return [];

  const classId = studentRow.class_id;

  // 2. Get term_dates for this org
  const termDatesResult = await db
    .prepare(
      `SELECT term_name, start_date, end_date, academic_year
       FROM term_dates
       WHERE organization_id = ?`
    )
    .bind(orgId)
    .all();
  const termDates = termDatesResult.results || [];

  // 3. Resolve current term
  const today = new Date().toISOString().slice(0, 10);
  const { term, startDate, endDate } = resolveCurrentTerm(termDates, today);

  // 4. Fetch goals to snapshot pre-update state
  const goalsBefore = await db
    .prepare(
      `SELECT id, metric, target, current, achieved_at
       FROM class_goals
       WHERE class_id = ? AND organization_id = ? AND term = ?`
    )
    .bind(classId, orgId, term)
    .all();

  const goalList = goalsBefore.results || [];
  if (goalList.length === 0) return [];

  const preUpdateNulls = new Set(goalList.filter((g) => g.achieved_at === null).map((g) => g.id));

  // 5. Recalculate
  await recalculateClassGoalProgress(db, classId, orgId, startDate, endDate, term);

  // 6. Re-read goals to find newly completed ones
  const goalsAfter = await db
    .prepare(
      `SELECT id, metric, target, current, achieved_at
       FROM class_goals
       WHERE class_id = ? AND organization_id = ? AND term = ?`
    )
    .bind(classId, orgId, term)
    .all();

  const newlyCompleted = (goalsAfter.results || []).filter(
    (g) => g.achieved_at !== null && preUpdateNulls.has(g.id)
  );

  return newlyCompleted.map(({ metric, target, current }) => ({ metric, target, current }));
}
