/**
 * Class Goals Engine — term resolution and goal recalculation.
 *
 * resolveCurrentTerm(termDates, today) — find which term today falls in
 * getAutoGeneratedTargets(classSize) — generate default targets from class size
 * recalculateClassGoalProgress(db, classId, orgId, startDate, endDate, term) — update counters
 * updateClassGoalOnSession(db, studentId, orgId) — full recalc after a session edit/delete
 * bumpClassGoalsOnSessions(db, studentId, orgId, newSessions) — cheap incremental
 *   update for the session-CREATE hot path (point lookups, no year scan)
 */

import { assertBatchSize } from './d1Batch.js';
import { ACADEMIC_YEAR_START_MONTH } from './constants.js';

// ── Term Resolution ─────────────────────────────────────────────────────────

/**
 * Calendar quarter boundaries (1-indexed month, inclusive).
 * Q1: Jan–Mar, Q2: Apr–Jun, Q3: Jul–Sep, Q4: Oct–Dec
 */
const QUARTERS = [
  { q: 'Q1', start: '01-01', end: '03-31' },
  { q: 'Q2', start: '04-01', end: '06-30' },
  { q: 'Q3', start: '07-01', end: '09-30' },
  { q: 'Q4', start: '10-01', end: '12-31' },
];

function calendarQuarterFallback(today) {
  const year = today.slice(0, 4);
  const mmdd = today.slice(5); // MM-DD
  for (const { q, start, end } of QUARTERS) {
    if (mmdd >= start && mmdd <= end) {
      return {
        term: `${q} ${year}`,
        startDate: `${year}-${start}`,
        endDate: `${year}-${end}`,
      };
    }
  }
  // Fallback safety: should never reach here with valid YYYY-MM-DD
  return { term: `Q4 ${year}`, startDate: `${year}-10-01`, endDate: `${year}-12-31` };
}

/**
 * Resolve the current term from an array of term_dates rows.
 *
 * @param {Array<{term_name: string, start_date: string, end_date: string, academic_year: string}>} termDates
 * @param {string} today - YYYY-MM-DD
 * @returns {{ term: string, startDate: string, endDate: string }}
 */
export function resolveCurrentTerm(termDates, today) {
  if (Array.isArray(termDates)) {
    for (const row of termDates) {
      if (today >= row.start_date && today <= row.end_date) {
        return {
          term: `${row.term_name} ${row.academic_year}`,
          startDate: row.start_date,
          endDate: row.end_date,
        };
      }
    }
  }
  return calendarQuarterFallback(today);
}

/**
 * Resolve the current academic year from term_dates.
 * Returns the full year range (earliest start to latest end) for goals.
 * Falls back to Sep–Aug cycle if no term_dates exist.
 */
export function resolveAcademicYear(termDates, today) {
  if (Array.isArray(termDates) && termDates.length > 0) {
    // Find which academic_year today falls in
    const currentTerm = termDates.find((r) => today >= r.start_date && today <= r.end_date);
    const academicYear =
      currentTerm?.academic_year || termDates[termDates.length - 1].academic_year;

    // Get all terms for this academic year
    const yearTerms = termDates.filter((r) => r.academic_year === academicYear);
    if (yearTerms.length > 0) {
      const starts = yearTerms.map((r) => r.start_date).sort();
      const ends = yearTerms.map((r) => r.end_date).sort();
      return {
        term: academicYear,
        startDate: starts[0],
        endDate: ends[ends.length - 1],
      };
    }
  }

  // Fallback: UK academic year Sep–Aug
  const year = parseInt(today.slice(0, 4));
  const month = parseInt(today.slice(5, 7));
  const startYear = month >= ACADEMIC_YEAR_START_MONTH ? year : year - 1;
  return {
    term: `${startYear}/${String(startYear + 1).slice(2)}`,
    startDate: `${startYear}-09-01`,
    endDate: `${startYear + 1}-08-31`,
  };
}

// ── Auto-Generated Targets ───────────────────────────────────────────────────

/**
 * Generate default goal targets from class size.
 *
 * @param {number} classSize
 * @returns {{ sessions: number, genres: number, books: number }}
 */
export function getAutoGeneratedTargets(classSize) {
  return {
    sessions: classSize * 20,
    genres: 10,
    books: classSize * 4,
    reading_days: 30,
    readers: classSize || 1,
    badges: classSize || 1,
  };
}

// ── Progress Recalculation ───────────────────────────────────────────────────

/**
 * Recalculate class goal progress by querying session, book, and genre counts,
 * then batch-updating the class_goals rows.
 *
 * @param {object} db - D1 database binding
 * @param {string} classId
 * @param {string} orgId
 * @param {string} startDate - YYYY-MM-DD (inclusive)
 * @param {string} endDate - YYYY-MM-DD (inclusive)
 * @param {string} term - term label (e.g. 'Spring 1 2025/26')
 */
export async function recalculateClassGoalProgress(db, classId, orgId, startDate, endDate, term) {
  // 1. Fetch existing goals for this class + term
  const goalsResult = await db
    .prepare(
      `SELECT id, metric, target, current, achieved_at
       FROM class_goals
       WHERE class_id = ? AND organization_id = ? AND term = ?`
    )
    .bind(classId, orgId, term)
    .all();

  const goals = goalsResult.results || [];
  if (goals.length === 0) return;

  // One round-trip instead of six. All session-derived counts share the same
  // class/org/date filter, and the badges count reuses the same class/org
  // scope. D1 runs each subquery independently but over one network hop.
  // Wrapped so a transient D1 failure doesn't take down the whole goals
  // endpoint — we keep the existing counters rather than overwriting them
  // with zeros. The next successful call reconciles.
  let countsRow;
  try {
    countsRow = await db
      .prepare(
        `SELECT
         (SELECT COUNT(DISTINCT rs.id)
            FROM reading_sessions rs
            JOIN students s ON rs.student_id = s.id
            WHERE s.class_id = ?1 AND s.organization_id = ?2
              AND rs.session_date >= ?3 AND rs.session_date <= ?4
              AND (rs.notes IS NULL OR (rs.notes NOT LIKE '%[ABSENT]%' AND rs.notes NOT LIKE '%[NO_RECORD]%'))) AS sessions,
         (SELECT COUNT(DISTINCT rs.book_id)
            FROM reading_sessions rs
            JOIN students s ON rs.student_id = s.id
            WHERE s.class_id = ?1 AND s.organization_id = ?2
              AND rs.session_date >= ?3 AND rs.session_date <= ?4
              AND rs.book_id IS NOT NULL
              AND (rs.notes IS NULL OR (rs.notes NOT LIKE '%[ABSENT]%' AND rs.notes NOT LIKE '%[NO_RECORD]%'))) AS books,
         (SELECT COUNT(DISTINCT je.value)
            FROM reading_sessions rs
            JOIN students s ON rs.student_id = s.id
            JOIN books b ON rs.book_id = b.id
            JOIN json_each(b.genre_ids) je
            WHERE s.class_id = ?1 AND s.organization_id = ?2
              AND rs.session_date >= ?3 AND rs.session_date <= ?4
              AND b.genre_ids IS NOT NULL
              AND (rs.notes IS NULL OR (rs.notes NOT LIKE '%[ABSENT]%' AND rs.notes NOT LIKE '%[NO_RECORD]%'))) AS genres,
         (SELECT COUNT(DISTINCT rs.session_date)
            FROM reading_sessions rs
            JOIN students s ON rs.student_id = s.id
            WHERE s.class_id = ?1 AND s.organization_id = ?2
              AND rs.session_date >= ?3 AND rs.session_date <= ?4
              AND (rs.notes IS NULL OR (rs.notes NOT LIKE '%[ABSENT]%' AND rs.notes NOT LIKE '%[NO_RECORD]%'))) AS reading_days,
         (SELECT COUNT(DISTINCT rs.student_id)
            FROM reading_sessions rs
            JOIN students s ON rs.student_id = s.id
            WHERE s.class_id = ?1 AND s.organization_id = ?2
              AND rs.session_date >= ?3 AND rs.session_date <= ?4
              AND (rs.notes IS NULL OR (rs.notes NOT LIKE '%[ABSENT]%' AND rs.notes NOT LIKE '%[NO_RECORD]%'))) AS readers,
         (SELECT COUNT(*)
            FROM student_badges sb
            JOIN students s ON sb.student_id = s.id
            WHERE s.class_id = ?1 AND s.organization_id = ?2
              AND sb.earned_at >= ?3 AND sb.earned_at <= ?4) AS badges`
      )
      .bind(classId, orgId, startDate, endDate)
      .first();
  } catch (err) {
    console.error('[classGoals] aggregate query failed — preserving prior counts', {
      classId,
      orgId,
      term,
      err: err?.message,
    });
    return;
  }

  const countsByMetric = {
    sessions: countsRow?.sessions ?? 0,
    books: countsRow?.books ?? 0,
    genres: countsRow?.genres ?? 0,
    reading_days: countsRow?.reading_days ?? 0,
    readers: countsRow?.readers ?? 0,
    badges: countsRow?.badges ?? 0,
  };

  const now = new Date().toISOString();

  // 5. Build UPDATE statements for each goal
  const updateStatements = goals.map((goal) => {
    const newCurrent = countsByMetric[goal.metric] ?? goal.current;
    // Set achieved_at only when newly crossing the threshold
    let newAchievedAt = goal.achieved_at;
    if (newCurrent >= goal.target && goal.achieved_at === null) {
      newAchievedAt = now;
    }
    return db
      .prepare(`UPDATE class_goals SET current = ?, achieved_at = ? WHERE id = ?`)
      .bind(newCurrent, newAchievedAt, goal.id);
  });

  // 6. Batch all updates
  assertBatchSize(updateStatements, 'classGoals recalculate');
  await db.batch(updateStatements);
}

// ── Session-triggered Update ─────────────────────────────────────────────────

/**
 * Called after a reading session is saved/deleted. Resolves the student's class,
 * finds the current term, and recalculates all goal progress for that class.
 * Returns newly-completed goals (those that crossed the threshold this call).
 *
 * @param {object} db - D1 database binding
 * @param {string} studentId
 * @param {string} orgId
 * @returns {Promise<Array<{metric: string, target: number, current: number}>>}
 */
export async function updateClassGoalOnSession(db, studentId, orgId) {
  // 1. Get student's class_id
  const studentRow = await db
    .prepare(`SELECT class_id FROM students WHERE id = ? AND organization_id = ?`)
    .bind(studentId, orgId)
    .first();

  if (!studentRow || !studentRow.class_id) return [];

  const classId = studentRow.class_id;

  // 2. Get term_dates for this org
  const termDatesResult = await db
    .prepare(
      `SELECT term_name, start_date, end_date, academic_year
       FROM term_dates
       WHERE organization_id = ?`
    )
    .bind(orgId)
    .all();
  const termDates = termDatesResult.results || [];

  // 3. Resolve academic year (goals span full year, not individual terms)
  const today = new Date().toISOString().slice(0, 10);
  const { term, startDate, endDate } = resolveAcademicYear(termDates, today);

  // 4. Fetch goals to snapshot pre-update state
  const goalsBefore = await db
    .prepare(
      `SELECT id, metric, target, current, achieved_at
       FROM class_goals
       WHERE class_id = ? AND organization_id = ? AND term = ?`
    )
    .bind(classId, orgId, term)
    .all();

  const goalList = goalsBefore.results || [];
  if (goalList.length === 0) return [];

  const preUpdateNulls = new Set(goalList.filter((g) => g.achieved_at === null).map((g) => g.id));

  // 5. Recalculate
  await recalculateClassGoalProgress(db, classId, orgId, startDate, endDate, term);

  // 6. Re-read goals to find newly completed ones
  const goalsAfter = await db
    .prepare(
      `SELECT id, metric, target, current, achieved_at
       FROM class_goals
       WHERE class_id = ? AND organization_id = ? AND term = ?`
    )
    .bind(classId, orgId, term)
    .all();

  const newlyCompleted = (goalsAfter.results || []).filter(
    (g) => g.achieved_at !== null && preUpdateNulls.has(g.id)
  );

  return newlyCompleted.map(({ metric, target, current }) => ({ metric, target, current }));
}

// ── Incremental Update (session-create hot path) ────────────────────────────

/**
 * Cheap incremental class-goal update for newly CREATED sessions.
 *
 * The full recalc (updateClassGoalOnSession) scans the class's entire academic
 * year of reading_sessions on every call — fine for rare edits/deletes and the
 * nightly cron, far too expensive on the per-tap session-create path. This
 * variant uses point lookups scoped to the new sessions only:
 *   - sessions:     += number of new non-marker sessions in range
 *   - readers:      +1 if this student had no other session in range
 *   - reading_days: += new dates with no other class session on that date
 *   - books:        += new distinct book_ids unused elsewhere in range
 *   - genres/badges: NOT incremented — they need global distinct counts.
 *     Drift is reconciled by the goals-view recalc (classes.js) and the
 *     nightly drift-correction cron.
 *
 * @param {object} db - D1 database binding
 * @param {string} studentId
 * @param {string} orgId
 * @param {Array<{id: string, date: string, bookId?: string|null, isMarker?: boolean}>} newSessions
 *   Sessions just inserted (ids must exist in reading_sessions).
 * @returns {Promise<Array<{metric: string, target: number, current: number}>>} newly-completed goals
 */
export async function bumpClassGoalsOnSessions(db, studentId, orgId, newSessions) {
  const real = (newSessions || []).filter((s) => s && !s.isMarker);
  if (real.length === 0) return [];

  // 1. Student's class
  const studentRow = await db
    .prepare(`SELECT class_id FROM students WHERE id = ? AND organization_id = ?`)
    .bind(studentId, orgId)
    .first();
  if (!studentRow || !studentRow.class_id) return [];
  const classId = studentRow.class_id;

  // 2. Academic-year window
  const termDatesResult = await db
    .prepare(
      `SELECT term_name, start_date, end_date, academic_year
       FROM term_dates
       WHERE organization_id = ?`
    )
    .bind(orgId)
    .all();
  const today = new Date().toISOString().slice(0, 10);
  const { term, startDate, endDate } = resolveAcademicYear(termDatesResult.results || [], today);

  // 3. Goals for this class + term (early exit when the class has none)
  const goalsResult = await db
    .prepare(
      `SELECT id, metric, target, current, achieved_at
       FROM class_goals
       WHERE class_id = ? AND organization_id = ? AND term = ?`
    )
    .bind(classId, orgId, term)
    .all();
  const goals = goalsResult.results || [];
  if (goals.length === 0) return [];

  const metrics = new Set(goals.map((g) => g.metric));
  const inRange = real.filter((s) => s.date >= startDate && s.date <= endDate);
  if (inRange.length === 0) return [];

  const newIds = inRange.map((s) => s.id);
  const idPh = newIds.map(() => '?').join(',');
  // NULL-safe marker exclusion (NULL NOT LIKE ... is NULL in SQLite, which
  // would silently drop notes-less rows — e.g. parent-portal sessions).
  const NON_MARKER = `(rs.notes IS NULL OR (rs.notes NOT LIKE '%[ABSENT]%' AND rs.notes NOT LIKE '%[NO_RECORD]%'))`;

  const increments = {};
  increments.sessions = inRange.length;

  // readers: +1 only if this student had no other non-marker session in range
  if (metrics.has('readers')) {
    const other = await db
      .prepare(
        `SELECT 1 FROM reading_sessions rs
          WHERE rs.student_id = ? AND rs.session_date >= ? AND rs.session_date <= ?
            AND rs.id NOT IN (${idPh}) AND ${NON_MARKER}
          LIMIT 1`
      )
      .bind(studentId, startDate, endDate, ...newIds)
      .first();
    increments.readers = other ? 0 : 1;
  }

  // reading_days: new dates with no other non-marker class session on that date
  if (metrics.has('reading_days')) {
    const dates = [...new Set(inRange.map((s) => s.date))];
    const datePh = dates.map(() => '?').join(',');
    const existing = await db
      .prepare(
        `SELECT DISTINCT rs.session_date AS d
           FROM reading_sessions rs
           JOIN students s ON rs.student_id = s.id
          WHERE s.class_id = ? AND s.organization_id = ?
            AND rs.session_date IN (${datePh})
            AND rs.id NOT IN (${idPh}) AND ${NON_MARKER}`
      )
      .bind(classId, orgId, ...dates, ...newIds)
      .all();
    const existingDates = new Set((existing.results || []).map((r) => r.d));
    increments.reading_days = dates.filter((d) => !existingDates.has(d)).length;
  }

  // books: new distinct book_ids not already read by the class this year
  if (metrics.has('books')) {
    const bookIds = [...new Set(inRange.map((s) => s.bookId).filter(Boolean))];
    if (bookIds.length > 0) {
      const bookPh = bookIds.map(() => '?').join(',');
      const existing = await db
        .prepare(
          `SELECT DISTINCT rs.book_id AS b
             FROM reading_sessions rs
             JOIN students s ON rs.student_id = s.id
            WHERE s.class_id = ? AND s.organization_id = ?
              AND rs.book_id IN (${bookPh})
              AND rs.session_date >= ? AND rs.session_date <= ?
              AND rs.id NOT IN (${idPh})`
        )
        .bind(classId, orgId, ...bookIds, startDate, endDate, ...newIds)
        .all();
      const existingBooks = new Set((existing.results || []).map((r) => r.b));
      increments.books = bookIds.filter((b) => !existingBooks.has(b)).length;
    }
  }

  // 4. Apply increments and detect newly-completed goals
  const now = new Date().toISOString();
  const updates = [];
  const newlyCompleted = [];
  for (const goal of goals) {
    const inc = increments[goal.metric] || 0;
    if (inc === 0) continue;
    const newCurrent = (goal.current || 0) + inc;
    let achievedAt = goal.achieved_at;
    if (newCurrent >= goal.target && goal.achieved_at === null) {
      achievedAt = now;
      newlyCompleted.push({ metric: goal.metric, target: goal.target, current: newCurrent });
    }
    updates.push(
      db
        .prepare(`UPDATE class_goals SET current = ?, achieved_at = ? WHERE id = ?`)
        .bind(newCurrent, achievedAt, goal.id)
    );
  }
  if (updates.length > 0) {
    assertBatchSize(updates, 'classGoals bump');
    await db.batch(updates);
  }
  return newlyCompleted;
}
