/**
 * Cross-tenant isolation tests.
 *
 * Static `WHERE organization_id = ?` checks have been audited many times
 * and look solid, but until 2026-05-08 there was no automated regression
 * test that authenticated as Org A and tried to access Org B's resources
 * by ID. This file is that regression net.
 *
 * Strategy: a smart mock D1 that knows which student/session/book belongs
 * to which org. Any `WHERE id = ? AND organization_id = ?` lookup for a
 * mismatched (id, org) pair returns null — the same behaviour real D1
 * would exhibit. We then call each `:id`-bearing route with Org B's
 * resource ID while authenticated as Org A's user and assert 404 (or 403
 * where appropriate). A 200 with foreign data would mean the route
 * silently dropped the org filter.
 *
 * If a route is added that takes an `:id` path param and operates on a
 * tenant-scoped resource, add it to the table here.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { Hono } from 'hono';

vi.mock('../../middleware/tenant', () => ({
  requireRole: () => (c, next) => next(),
  requireAdmin: () => (c, next) => next(),
  requireTeacher: () => (c, next) => next(),
  requireReadonly: () => (c, next) => next(),
  auditLog: () => (c, next) => next(),
}));

vi.mock('../../middleware/errorHandler', async () => {
  const actual = await vi.importActual('../../middleware/errorHandler');
  return actual;
});

vi.mock('../../utils/routeHelpers', async (importOriginal) => {
  const actual = await importOriginal();
  return {
    ...actual,
    getDB: (env) => env.READING_MANAGER_DB,
    isMultiTenantMode: () => true,
  };
});

vi.mock('../../utils/crypto', () => ({
  permissions: {
    MANAGE_STUDENTS: 'manage_students',
    canManageStudents: () => true,
    canManageBooks: () => true,
    canManageClasses: () => true,
    canManageOrganization: () => true,
    canManageUsers: () => true,
    canViewStudents: () => true,
  },
  ROLES: { OWNER: 'owner', ADMIN: 'admin', TEACHER: 'teacher', READONLY: 'readonly' },
}));

vi.mock('../../utils/validation', () => ({
  validateStudent: () => ({ isValid: true }),
  validateReadingLevelRange: () => ({ isValid: true }),
  validateSessionInput: (body) => ({ isValid: true, error: '', data: { ...body } }),
}));

vi.mock('../../services/kvService', () => ({
  getStudents: vi.fn().mockResolvedValue([]),
  getStudentById: vi.fn().mockResolvedValue(null),
  saveStudent: vi.fn().mockResolvedValue({}),
  deleteStudent: vi.fn().mockResolvedValue({}),
  addStudents: vi.fn().mockResolvedValue([]),
}));

vi.mock('../../utils/helpers', () => ({
  generateId: () => 'generated-id',
  csvRow: (values) => values.map((v) => (v == null ? '' : String(v))).join(','),
}));

vi.mock('../../utils/streakCalculator', () => ({
  calculateStreak: () => ({ currentStreak: 0, longestStreak: 0, streakStartDate: null }),
  getDateString: () => '2026-05-08',
}));

vi.mock('../../utils/badgeEngine', () => ({
  recalculateStats: vi.fn().mockResolvedValue({}),
  evaluateRealTime: vi.fn().mockResolvedValue([]),
  evaluateBatch: vi.fn().mockResolvedValue([]),
  calculateNearMisses: vi.fn().mockReturnValue([]),
}));

vi.mock('../../utils/classGoalsEngine.js', () => ({
  updateClassGoalOnSession: vi.fn().mockResolvedValue([]),
  recalculateClassGoalProgress: vi.fn().mockResolvedValue({}),
  resolveCurrentTerm: () => ({
    termName: 'Spring',
    startDate: '2026-01-01',
    endDate: '2026-04-01',
  }),
  resolveAcademicYear: () => '2025-2026',
  getAutoGeneratedTargets: () => ({}),
}));

vi.mock('../../routes/students/_shared.js', () => ({
  fetchStudentPreferences: vi.fn().mockResolvedValue({ likes: [], dislikes: [] }),
  saveStudentPreferences: vi.fn().mockResolvedValue({}),
  getOrgStreakSettings: vi.fn().mockResolvedValue({ timezone: 'UTC', graceDays: 1 }),
  updateStudentStreak: vi.fn().mockResolvedValue({}),
  updateStudentBand: vi.fn().mockResolvedValue({ currentBand: 0, readsCount: 0, bandUp: null }),
  ensureCurrentBand: vi
    .fn()
    .mockResolvedValue({ currentBand: 0, bandReadsCount: 0, recomputed: false }),
}));

import { studentsRouter } from '../../routes/students.js';

const ORG_A = 'org-A';
const ORG_B = 'org-B';
const STUDENT_A = 'student-A1';
const STUDENT_B = 'student-B1';
const SESSION_B = 'session-B1';

/**
 * Build a mock D1 such that:
 *   - student-A1 belongs to org-A
 *   - student-B1 belongs to org-B
 *   - session-B1 belongs to student-B1 (and therefore org-B)
 *
 * Queries that bind a (studentId, orgId) pair return the row only if
 * the binding matches the registered owner. Org-mismatched queries
 * return null — exactly what real D1 with `WHERE org_id = ?` does.
 */
const buildIsolatedDB = () => {
  const studentToOrg = { [STUDENT_A]: ORG_A, [STUDENT_B]: ORG_B };
  const sessionToStudent = { [SESSION_B]: STUDENT_B };

  const lookupStudent = (boundArgs) => {
    // `WHERE id = ? AND organization_id = ?` patterns
    const [first, second] = boundArgs;
    const studentId = first;
    const orgId = second;
    const owner = studentToOrg[studentId];
    if (owner && owner === orgId) {
      return {
        id: studentId,
        organization_id: orgId,
        name: `${studentId}-name`,
        is_active: 1,
        processing_restricted: 0,
        ai_opt_out: 0,
        wonde_student_id: null,
        year_group: '4',
      };
    }
    return null;
  };

  const lookupSession = (boundArgs) => {
    const [sessionId, studentId] = boundArgs;
    if (sessionToStudent[sessionId] !== studentId) return null;
    return {
      id: sessionId,
      student_id: studentId,
      session_date: '2026-05-08',
      book_id: null,
      pages_read: 10,
      duration_minutes: 15,
      assessment: 3,
      notes: null,
      location: 'school',
      recorded_by: 'someone',
    };
  };

  // Track every (sql, boundArgs) prepare so tests can assert what was queried
  const queries = [];

  const prepare = vi.fn((sql) => {
    let boundArgs = [];
    const chain = {
      bind: vi.fn((...args) => {
        boundArgs = args;
        queries.push({ sql, args });
        return chain;
      }),
      first: vi.fn(() => {
        if (sql.includes('FROM students') && sql.includes('organization_id')) {
          return Promise.resolve(lookupStudent(boundArgs));
        }
        if (sql.includes('FROM students')) {
          // Bare student lookup (no org filter) — should not happen on
          // tenant-scoped routes. Return null so we surface the bug.
          return Promise.resolve(null);
        }
        if (sql.includes('FROM reading_sessions')) {
          return Promise.resolve(lookupSession(boundArgs));
        }
        if (sql.includes('FROM org_book_selections')) {
          return Promise.resolve({ 1: 1 });
        }
        if (sql.includes('SELECT COUNT(*) as count')) {
          return Promise.resolve({ count: 0 });
        }
        return Promise.resolve(null);
      }),
      all: vi.fn(() => Promise.resolve({ results: [], success: true })),
      run: vi.fn(() => Promise.resolve({ success: true, meta: { changes: 0 } })),
    };
    return chain;
  });

  return {
    prepare,
    batch: vi.fn().mockResolvedValue([{ success: true }]),
    _queries: queries,
  };
};

const buildAppAsOrgA = (mockDB) => {
  const app = new Hono();
  app.onError((error, c) =>
    c.json({ status: 'error', message: error.message }, error.status || 500)
  );
  app.use('*', async (c, next) => {
    c.env = { READING_MANAGER_DB: mockDB, JWT_SECRET: 'test-secret' };
    c.set('organizationId', ORG_A);
    c.set('userId', 'user-A');
    c.set('userRole', 'admin');
    await next();
  });
  app.route('/api/students', studentsRouter);
  return app;
};

const makeRequest = async (app, method, path, body = null) => {
  const options = { method, headers: { 'Content-Type': 'application/json' } };
  if (body !== null) options.body = JSON.stringify(body);
  return app.request(path, options);
};

describe('Cross-tenant isolation — :id-bearing student routes', () => {
  let mockDB;
  let app;

  beforeEach(() => {
    mockDB = buildIsolatedDB();
    app = buildAppAsOrgA(mockDB);
  });

  // Each entry: [label, method, path-with-foreign-id, body]
  // path uses STUDENT_B (foreign) — the request is made as ORG_A.
  const foreignRoutes = [
    ['GET /:id (read)', 'GET', `/api/students/${STUDENT_B}`, null],
    [
      'PUT /:id (update)',
      'PUT',
      `/api/students/${STUDENT_B}`,
      { name: 'attacker-set-name', readingLevelMin: 5, readingLevelMax: 6 },
    ],
    ['DELETE /:id (soft-delete)', 'DELETE', `/api/students/${STUDENT_B}`, null],
    [
      'PUT /:id/current-book',
      'PUT',
      `/api/students/${STUDENT_B}/current-book`,
      { bookId: 'book-1' },
    ],
    [
      'PUT /:id/feedback',
      'PUT',
      `/api/students/${STUDENT_B}/feedback`,
      { type: 'like', value: 'Foo' },
    ],
    ['GET /:id/streak', 'GET', `/api/students/${STUDENT_B}/streak`, null],
    [
      'POST /:id/sessions (create)',
      'POST',
      `/api/students/${STUDENT_B}/sessions`,
      { bookTitle: 'Foo', assessment: 3 },
    ],
    [
      'PUT /:id/sessions/:sessionId (update)',
      'PUT',
      `/api/students/${STUDENT_B}/sessions/${SESSION_B}`,
      { bookTitle: 'Foo', assessment: 3 },
    ],
    [
      'DELETE /:id/sessions/:sessionId',
      'DELETE',
      `/api/students/${STUDENT_B}/sessions/${SESSION_B}`,
      null,
    ],
    [
      'DELETE /:id/erase (GDPR Article 17)',
      'DELETE',
      `/api/students/${STUDENT_B}/erase`,
      { confirm: true },
    ],
    [
      'PUT /:id/restrict (GDPR Article 18)',
      'PUT',
      `/api/students/${STUDENT_B}/restrict`,
      { restricted: true },
    ],
    ['PUT /:id/ai-opt-out', 'PUT', `/api/students/${STUDENT_B}/ai-opt-out`, { aiOptOut: true }],
    ['GET /:id/export (Article 15 SAR)', 'GET', `/api/students/${STUDENT_B}/export`, null],
  ];

  for (const [label, method, path, body] of foreignRoutes) {
    it(`refuses cross-tenant access on ${label}`, async () => {
      const res = await makeRequest(app, method, path, body);

      // Must not return success with foreign data. 404 (resource not in
      // this org's scope) is the canonical answer; 403 is acceptable; any
      // 4xx is OK; 5xx is a different bug class.
      expect(res.status).toBeGreaterThanOrEqual(400);
      expect(res.status).toBeLessThan(500);

      // Crucially never return Org B's data
      const text = await res.text();
      expect(text).not.toContain('attacker-set-name');
      // No batch mutation should have run on a foreign-tenant request
      expect(mockDB.batch).not.toHaveBeenCalled();
    });
  }

  it('sanity check: same routes succeed for the caller-owned student', async () => {
    // If THIS test fails, the cross-tenant tests above are false-positives
    // (routes are returning 404 for legitimate access too)
    const res = await makeRequest(app, 'GET', `/api/students/${STUDENT_A}`);
    expect(res.status).toBeLessThan(400);
  });

  it('every cross-tenant query passes organizationId in the bind', async () => {
    // Smoke test: if a future refactor accidentally drops `organization_id`
    // from a `WHERE id = ? AND organization_id = ?` clause, this assertion
    // catches it. The buildIsolatedDB tracks every prepare/bind pair.
    // For each query that touched the students table, assert the bind
    // included our org id.
    await makeRequest(app, 'GET', `/api/students/${STUDENT_B}`);

    const studentQueries = mockDB._queries.filter(
      (q) => q.sql.includes('FROM students') && q.sql.includes('organization_id')
    );
    expect(studentQueries.length).toBeGreaterThan(0);
    for (const q of studentQueries) {
      expect(q.args).toContain(ORG_A);
    }
  });
});
