import { describe, it, expect, vi } from 'vitest';
import {
  resolveCurrentTerm,
  getAutoGeneratedTargets,
  recalculateClassGoalProgress,
  bumpClassGoalsOnSessions,
} from '../../utils/classGoalsEngine.js';

describe('resolveCurrentTerm', () => {
  it('returns matching half-term from term_dates', () => {
    const termDates = [
      {
        term_name: 'Autumn 1',
        start_date: '2025-09-01',
        end_date: '2025-10-25',
        academic_year: '2025/26',
      },
      {
        term_name: 'Spring 1',
        start_date: '2026-01-05',
        end_date: '2026-02-14',
        academic_year: '2025/26',
      },
      {
        term_name: 'Spring 2',
        start_date: '2026-02-24',
        end_date: '2026-04-10',
        academic_year: '2025/26',
      },
    ];
    const result = resolveCurrentTerm(termDates, '2026-03-15');
    expect(result).toEqual({
      term: 'Spring 2 2025/26',
      startDate: '2026-02-24',
      endDate: '2026-04-10',
    });
  });

  it('falls back to calendar quarter when no term_dates match', () => {
    const result = resolveCurrentTerm([], '2026-04-08');
    expect(result.term).toBe('Q2 2026');
    expect(result.startDate).toBe('2026-04-01');
    expect(result.endDate).toBe('2026-06-30');
  });

  it('falls back when date is outside all terms', () => {
    const termDates = [
      {
        term_name: 'Autumn 1',
        start_date: '2025-09-01',
        end_date: '2025-10-25',
        academic_year: '2025/26',
      },
    ];
    const result = resolveCurrentTerm(termDates, '2026-07-15');
    expect(result.term).toBe('Q3 2026');
  });

  it('matches start boundary (inclusive)', () => {
    const termDates = [
      {
        term_name: 'Summer 1',
        start_date: '2026-04-21',
        end_date: '2026-05-26',
        academic_year: '2025/26',
      },
    ];
    const result = resolveCurrentTerm(termDates, '2026-04-21');
    expect(result.term).toBe('Summer 1 2025/26');
  });

  it('matches end boundary (inclusive)', () => {
    const termDates = [
      {
        term_name: 'Summer 1',
        start_date: '2026-04-21',
        end_date: '2026-05-26',
        academic_year: '2025/26',
      },
    ];
    const result = resolveCurrentTerm(termDates, '2026-05-26');
    expect(result.term).toBe('Summer 1 2025/26');
  });

  it('returns Q1 for January', () => {
    const result = resolveCurrentTerm([], '2026-01-15');
    expect(result.term).toBe('Q1 2026');
    expect(result.startDate).toBe('2026-01-01');
    expect(result.endDate).toBe('2026-03-31');
  });

  it('returns Q4 for November', () => {
    const result = resolveCurrentTerm([], '2026-11-10');
    expect(result.term).toBe('Q4 2026');
    expect(result.startDate).toBe('2026-10-01');
    expect(result.endDate).toBe('2026-12-31');
  });
});

describe('getAutoGeneratedTargets', () => {
  it('generates targets based on class size', () => {
    expect(getAutoGeneratedTargets(26)).toEqual({
      sessions: 520,
      genres: 10,
      books: 104,
      reading_days: 30,
      readers: 26,
      badges: 26,
    });
  });

  it('handles zero class size', () => {
    expect(getAutoGeneratedTargets(0)).toEqual({
      sessions: 0,
      genres: 10,
      books: 0,
      reading_days: 30,
      readers: 1,
      badges: 1,
    });
  });

  it('handles a small class', () => {
    expect(getAutoGeneratedTargets(5)).toEqual({
      sessions: 100,
      genres: 10,
      books: 20,
      reading_days: 30,
      readers: 5,
      badges: 5,
    });
  });

  it('always returns genres: 10 regardless of class size', () => {
    expect(getAutoGeneratedTargets(1).genres).toBe(10);
    expect(getAutoGeneratedTargets(100).genres).toBe(10);
  });
});

describe('recalculateClassGoalProgress', () => {
  it('updates goal counters from source data', async () => {
    const batchedStatements = [];
    const mockDb = {
      prepare: vi.fn((sql) => ({
        bind: vi.fn(() => ({
          first: vi.fn(() => {
            if (
              sql.includes('COUNT') &&
              sql.includes('reading_sessions') &&
              !sql.includes('book_id') &&
              !sql.includes('json_each')
            ) {
              return { count: 42 };
            }
            if (sql.includes('COUNT') && sql.includes('book_id') && !sql.includes('json_each')) {
              return { count: 15 };
            }
            if (sql.includes('COUNT') && sql.includes('json_each')) {
              return { count: 8 };
            }
            return null;
          }),
          all: vi.fn(() => {
            if (sql.includes('class_goals')) {
              return {
                results: [
                  { id: 'g1', metric: 'sessions', target: 500, current: 0, achieved_at: null },
                  { id: 'g2', metric: 'books', target: 100, current: 0, achieved_at: null },
                  { id: 'g3', metric: 'genres', target: 10, current: 0, achieved_at: null },
                ],
              };
            }
            return { results: [] };
          }),
          run: vi.fn(),
        })),
      })),
      batch: vi.fn((stmts) => {
        batchedStatements.push(...stmts);
        return stmts.map(() => ({ success: true }));
      }),
    };

    await recalculateClassGoalProgress(
      mockDb,
      'c1',
      'org1',
      '2026-01-01',
      '2026-04-10',
      'Spring 1 2025/26'
    );
    expect(mockDb.batch).toHaveBeenCalled();
    // 3 UPDATE statements (one per goal)
    expect(mockDb.batch.mock.calls[0][0]).toHaveLength(3);
  });

  it('skips when no goals exist', async () => {
    const mockDb = {
      prepare: vi.fn(() => ({
        bind: vi.fn(() => ({
          all: vi.fn(() => ({ results: [] })),
        })),
      })),
      batch: vi.fn(),
    };

    await recalculateClassGoalProgress(
      mockDb,
      'c1',
      'org1',
      '2026-01-01',
      '2026-04-10',
      'Spring 1 2025/26'
    );
    expect(mockDb.batch).not.toHaveBeenCalled();
  });

  it('sets achieved_at when goal is newly completed', async () => {
    const capturedStatements = [];
    const mockDb = {
      prepare: vi.fn((sql) => ({
        bind: vi.fn((...args) => {
          const _stmt = { sql, args, boundArgs: args };
          return {
            first: vi.fn(() => {
              if (sql.includes('COUNT') && !sql.includes('book_id') && !sql.includes('json_each')) {
                return { count: 600 }; // exceeds target of 500
              }
              if (sql.includes('COUNT') && sql.includes('book_id') && !sql.includes('json_each')) {
                return { count: 5 };
              }
              if (sql.includes('COUNT') && sql.includes('json_each')) {
                return { count: 3 };
              }
              return null;
            }),
            all: vi.fn(() => {
              if (sql.includes('class_goals')) {
                return {
                  results: [
                    { id: 'g1', metric: 'sessions', target: 500, current: 400, achieved_at: null },
                  ],
                };
              }
              return { results: [] };
            }),
            run: vi.fn(),
          };
        }),
      })),
      batch: vi.fn((stmts) => {
        capturedStatements.push(...stmts);
        return stmts.map(() => ({ success: true }));
      }),
    };

    await recalculateClassGoalProgress(
      mockDb,
      'c1',
      'org1',
      '2026-01-01',
      '2026-04-10',
      'Spring 1 2025/26'
    );
    expect(mockDb.batch).toHaveBeenCalledOnce();
    // The batch call should contain one statement (for g1)
    const batchCall = mockDb.batch.mock.calls[0][0];
    expect(batchCall).toHaveLength(1);
  });

  it('preserves existing achieved_at when goal was already completed', async () => {
    const existingAchievedAt = '2026-02-01T10:00:00.000Z';
    const mockDb = {
      prepare: vi.fn((sql) => ({
        bind: vi.fn((..._args) => ({
          first: vi.fn(() => {
            if (sql.includes('COUNT') && !sql.includes('book_id') && !sql.includes('json_each')) {
              return { count: 600 };
            }
            if (sql.includes('COUNT') && sql.includes('book_id') && !sql.includes('json_each')) {
              return { count: 5 };
            }
            if (sql.includes('COUNT') && sql.includes('json_each')) {
              return { count: 3 };
            }
            return null;
          }),
          all: vi.fn(() => {
            if (sql.includes('class_goals')) {
              return {
                results: [
                  {
                    id: 'g1',
                    metric: 'sessions',
                    target: 500,
                    current: 550,
                    achieved_at: existingAchievedAt,
                  },
                ],
              };
            }
            return { results: [] };
          }),
          run: vi.fn(),
        })),
      })),
      batch: vi.fn((stmts) => stmts.map(() => ({ success: true }))),
    };

    await recalculateClassGoalProgress(
      mockDb,
      'c1',
      'org1',
      '2026-01-01',
      '2026-04-10',
      'Spring 1 2025/26'
    );
    expect(mockDb.batch).toHaveBeenCalledOnce();
    // Batch should still be called with update statements
    const batchCall = mockDb.batch.mock.calls[0][0];
    expect(batchCall).toHaveLength(1);
  });
});

describe('bumpClassGoalsOnSessions', () => {
  // Mock DB factory keyed by SQL content. `pointResults` controls the
  // uniqueness point-checks; `goals` the class_goals rows.
  const createBumpMockDb = ({ goals, readerHasOther = null, existingDates = [], existingBooks = [] }) => {
    const batched = [];
    const db = {
      prepare: vi.fn((sql) => ({
        bind: vi.fn((...args) => ({
          first: vi.fn(() => {
            if (sql.includes('class_id FROM students')) return { class_id: 'c1' };
            if (sql.includes('rs.student_id = ?') && sql.includes('LIMIT 1')) {
              return readerHasOther;
            }
            return null;
          }),
          all: vi.fn(() => {
            if (sql.includes('FROM term_dates')) return { results: [] };
            if (sql.includes('FROM class_goals')) return { results: goals };
            if (sql.includes('DISTINCT rs.session_date')) {
              return { results: existingDates.map((d) => ({ d })) };
            }
            if (sql.includes('DISTINCT rs.book_id')) {
              return { results: existingBooks.map((b) => ({ b })) };
            }
            return { results: [] };
          }),
          run: vi.fn(),
          _args: args,
        })),
      })),
      batch: vi.fn((stmts) => {
        batched.push(...stmts);
        return stmts.map(() => ({ success: true }));
      }),
      _batched: batched,
    };
    return db;
  };

  // Sessions dated "today" so they always fall inside the resolved
  // academic-year window regardless of when the test runs.
  const today = new Date().toISOString().slice(0, 10);

  it('increments the sessions metric by the number of new non-marker sessions', async () => {
    const db = createBumpMockDb({
      goals: [{ id: 'g1', metric: 'sessions', target: 500, current: 10, achieved_at: null }],
    });

    const result = await bumpClassGoalsOnSessions(db, 'student-1', 'org-1', [
      { id: 's1', date: today, bookId: null, isMarker: false },
      { id: 's2', date: today, bookId: null, isMarker: false },
      { id: 's3', date: today, bookId: null, isMarker: true }, // markers excluded
    ]);

    expect(db.batch).toHaveBeenCalledTimes(1);
    const update = db.batch.mock.calls[0][0][0];
    // current 10 + 2 new non-marker sessions = 12
    expect(update._args[0]).toBe(12);
    expect(result).toEqual([]); // not completed yet
  });

  it('returns newly-completed goals when the increment crosses the target', async () => {
    const db = createBumpMockDb({
      goals: [{ id: 'g1', metric: 'sessions', target: 12, current: 11, achieved_at: null }],
    });

    const result = await bumpClassGoalsOnSessions(db, 'student-1', 'org-1', [
      { id: 's1', date: today, bookId: null, isMarker: false },
    ]);

    expect(result).toEqual([{ metric: 'sessions', target: 12, current: 12 }]);
    const update = db.batch.mock.calls[0][0][0];
    expect(update._args[1]).not.toBeNull(); // achieved_at stamped
  });

  it('does not re-complete an already-achieved goal', async () => {
    const db = createBumpMockDb({
      goals: [{ id: 'g1', metric: 'sessions', target: 10, current: 15, achieved_at: '2026-01-01' }],
    });

    const result = await bumpClassGoalsOnSessions(db, 'student-1', 'org-1', [
      { id: 's1', date: today, bookId: null, isMarker: false },
    ]);
    expect(result).toEqual([]);
  });

  it('increments readers only when the student has no other session in range', async () => {
    const goals = [{ id: 'g1', metric: 'readers', target: 30, current: 5, achieved_at: null }];

    const dbNew = createBumpMockDb({ goals, readerHasOther: null });
    await bumpClassGoalsOnSessions(dbNew, 'student-1', 'org-1', [
      { id: 's1', date: today, isMarker: false },
    ]);
    expect(dbNew.batch.mock.calls[0][0][0]._args[0]).toBe(6); // +1

    const dbExisting = createBumpMockDb({ goals, readerHasOther: { 1: 1 } });
    await bumpClassGoalsOnSessions(dbExisting, 'student-1', 'org-1', [
      { id: 's1', date: today, isMarker: false },
    ]);
    // increment is 0 -> no update statement at all
    expect(dbExisting.batch).not.toHaveBeenCalled();
  });

  it('counts only genuinely new reading days', async () => {
    const goals = [{ id: 'g1', metric: 'reading_days', target: 100, current: 20, achieved_at: null }];
    // One of the two batch dates already has a class session
    const db = createBumpMockDb({ goals, existingDates: [today] });

    const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
    await bumpClassGoalsOnSessions(db, 'student-1', 'org-1', [
      { id: 's1', date: today, isMarker: false },
      { id: 's2', date: yesterday, isMarker: false },
    ]);

    // Only yesterday is a new reading day -> 20 + 1
    const updates = db.batch.mock.calls[0][0];
    const rd = updates.find((u) => u._args[0] === 21);
    expect(rd).toBeTruthy();
  });

  it('counts only book ids unused elsewhere in range', async () => {
    const goals = [{ id: 'g1', metric: 'books', target: 50, current: 7, achieved_at: null }];
    const db = createBumpMockDb({ goals, existingBooks: ['book-known'] });

    await bumpClassGoalsOnSessions(db, 'student-1', 'org-1', [
      { id: 's1', date: today, bookId: 'book-known', isMarker: false },
      { id: 's2', date: today, bookId: 'book-new', isMarker: false },
    ]);

    // Only book-new increments -> 7 + 1
    expect(db.batch.mock.calls[0][0][0]._args[0]).toBe(8);
  });

  it('returns early with no queries beyond goals when class has no goals', async () => {
    const db = createBumpMockDb({ goals: [] });
    const result = await bumpClassGoalsOnSessions(db, 'student-1', 'org-1', [
      { id: 's1', date: today, isMarker: false },
    ]);
    expect(result).toEqual([]);
    expect(db.batch).not.toHaveBeenCalled();
  });

  it('returns early when all sessions are markers', async () => {
    const db = createBumpMockDb({
      goals: [{ id: 'g1', metric: 'sessions', target: 10, current: 1, achieved_at: null }],
    });
    const result = await bumpClassGoalsOnSessions(db, 'student-1', 'org-1', [
      { id: 's1', date: today, isMarker: true },
    ]);
    expect(result).toEqual([]);
    expect(db.prepare).not.toHaveBeenCalled();
  });
});
