import { describe, it, expect, vi } from 'vitest';
import {
  resolveCurrentTerm,
  getAutoGeneratedTargets,
  recalculateClassGoalProgress,
} from '../../utils/classGoalsEngine.js';

describe('resolveCurrentTerm', () => {
  it('returns matching half-term from term_dates', () => {
    const termDates = [
      { term_name: 'Autumn 1', start_date: '2025-09-01', end_date: '2025-10-25', academic_year: '2025/26' },
      { term_name: 'Spring 1', start_date: '2026-01-05', end_date: '2026-02-14', academic_year: '2025/26' },
      { term_name: 'Spring 2', start_date: '2026-02-24', end_date: '2026-04-10', academic_year: '2025/26' },
    ];
    const result = resolveCurrentTerm(termDates, '2026-03-15');
    expect(result).toEqual({ term: 'Spring 2 2025/26', startDate: '2026-02-24', endDate: '2026-04-10' });
  });

  it('falls back to calendar quarter when no term_dates match', () => {
    const result = resolveCurrentTerm([], '2026-04-08');
    expect(result.term).toBe('Q2 2026');
    expect(result.startDate).toBe('2026-04-01');
    expect(result.endDate).toBe('2026-06-30');
  });

  it('falls back when date is outside all terms', () => {
    const termDates = [
      { term_name: 'Autumn 1', start_date: '2025-09-01', end_date: '2025-10-25', academic_year: '2025/26' },
    ];
    const result = resolveCurrentTerm(termDates, '2026-07-15');
    expect(result.term).toBe('Q3 2026');
  });

  it('matches start boundary (inclusive)', () => {
    const termDates = [
      { term_name: 'Summer 1', start_date: '2026-04-21', end_date: '2026-05-26', academic_year: '2025/26' },
    ];
    const result = resolveCurrentTerm(termDates, '2026-04-21');
    expect(result.term).toBe('Summer 1 2025/26');
  });

  it('matches end boundary (inclusive)', () => {
    const termDates = [
      { term_name: 'Summer 1', start_date: '2026-04-21', end_date: '2026-05-26', academic_year: '2025/26' },
    ];
    const result = resolveCurrentTerm(termDates, '2026-05-26');
    expect(result.term).toBe('Summer 1 2025/26');
  });

  it('returns Q1 for January', () => {
    const result = resolveCurrentTerm([], '2026-01-15');
    expect(result.term).toBe('Q1 2026');
    expect(result.startDate).toBe('2026-01-01');
    expect(result.endDate).toBe('2026-03-31');
  });

  it('returns Q4 for November', () => {
    const result = resolveCurrentTerm([], '2026-11-10');
    expect(result.term).toBe('Q4 2026');
    expect(result.startDate).toBe('2026-10-01');
    expect(result.endDate).toBe('2026-12-31');
  });
});

describe('getAutoGeneratedTargets', () => {
  it('generates targets based on class size', () => {
    expect(getAutoGeneratedTargets(26)).toEqual({ sessions: 520, genres: 10, books: 104 });
  });

  it('handles zero class size', () => {
    expect(getAutoGeneratedTargets(0)).toEqual({ sessions: 0, genres: 10, books: 0 });
  });

  it('handles a small class', () => {
    expect(getAutoGeneratedTargets(5)).toEqual({ sessions: 100, genres: 10, books: 20 });
  });

  it('always returns genres: 10 regardless of class size', () => {
    expect(getAutoGeneratedTargets(1).genres).toBe(10);
    expect(getAutoGeneratedTargets(100).genres).toBe(10);
  });
});

describe('recalculateClassGoalProgress', () => {
  it('updates goal counters from source data', async () => {
    const batchedStatements = [];
    const mockDb = {
      prepare: vi.fn((sql) => ({
        bind: vi.fn(() => ({
          first: vi.fn(() => {
            if (sql.includes('COUNT') && sql.includes('reading_sessions') && !sql.includes('book_id') && !sql.includes('json_each')) {
              return { count: 42 };
            }
            if (sql.includes('COUNT') && sql.includes('book_id') && !sql.includes('json_each')) {
              return { count: 15 };
            }
            if (sql.includes('COUNT') && sql.includes('json_each')) {
              return { count: 8 };
            }
            return null;
          }),
          all: vi.fn(() => {
            if (sql.includes('class_goals')) {
              return {
                results: [
                  { id: 'g1', metric: 'sessions', target: 500, current: 0, achieved_at: null },
                  { id: 'g2', metric: 'books', target: 100, current: 0, achieved_at: null },
                  { id: 'g3', metric: 'genres', target: 10, current: 0, achieved_at: null },
                ],
              };
            }
            return { results: [] };
          }),
          run: vi.fn(),
        })),
      })),
      batch: vi.fn((stmts) => {
        batchedStatements.push(...stmts);
        return stmts.map(() => ({ success: true }));
      }),
    };

    await recalculateClassGoalProgress(mockDb, 'c1', 'org1', '2026-01-01', '2026-04-10', 'Spring 1 2025/26');
    expect(mockDb.batch).toHaveBeenCalled();
    // 3 UPDATE statements (one per goal)
    expect(mockDb.batch.mock.calls[0][0]).toHaveLength(3);
  });

  it('skips when no goals exist', async () => {
    const mockDb = {
      prepare: vi.fn(() => ({
        bind: vi.fn(() => ({
          all: vi.fn(() => ({ results: [] })),
        })),
      })),
      batch: vi.fn(),
    };

    await recalculateClassGoalProgress(mockDb, 'c1', 'org1', '2026-01-01', '2026-04-10', 'Spring 1 2025/26');
    expect(mockDb.batch).not.toHaveBeenCalled();
  });

  it('sets achieved_at when goal is newly completed', async () => {
    const capturedStatements = [];
    const mockDb = {
      prepare: vi.fn((sql) => ({
        bind: vi.fn((...args) => {
          const stmt = { sql, args, boundArgs: args };
          return {
            first: vi.fn(() => {
              if (sql.includes('COUNT') && !sql.includes('book_id') && !sql.includes('json_each')) {
                return { count: 600 }; // exceeds target of 500
              }
              if (sql.includes('COUNT') && sql.includes('book_id') && !sql.includes('json_each')) {
                return { count: 5 };
              }
              if (sql.includes('COUNT') && sql.includes('json_each')) {
                return { count: 3 };
              }
              return null;
            }),
            all: vi.fn(() => {
              if (sql.includes('class_goals')) {
                return {
                  results: [
                    { id: 'g1', metric: 'sessions', target: 500, current: 400, achieved_at: null },
                  ],
                };
              }
              return { results: [] };
            }),
            run: vi.fn(),
          };
        }),
      })),
      batch: vi.fn((stmts) => {
        capturedStatements.push(...stmts);
        return stmts.map(() => ({ success: true }));
      }),
    };

    await recalculateClassGoalProgress(mockDb, 'c1', 'org1', '2026-01-01', '2026-04-10', 'Spring 1 2025/26');
    expect(mockDb.batch).toHaveBeenCalledOnce();
    // The batch call should contain one statement (for g1)
    const batchCall = mockDb.batch.mock.calls[0][0];
    expect(batchCall).toHaveLength(1);
  });

  it('preserves existing achieved_at when goal was already completed', async () => {
    const existingAchievedAt = '2026-02-01T10:00:00.000Z';
    const mockDb = {
      prepare: vi.fn((sql) => ({
        bind: vi.fn((...args) => ({
          first: vi.fn(() => {
            if (sql.includes('COUNT') && !sql.includes('book_id') && !sql.includes('json_each')) {
              return { count: 600 };
            }
            if (sql.includes('COUNT') && sql.includes('book_id') && !sql.includes('json_each')) {
              return { count: 5 };
            }
            if (sql.includes('COUNT') && sql.includes('json_each')) {
              return { count: 3 };
            }
            return null;
          }),
          all: vi.fn(() => {
            if (sql.includes('class_goals')) {
              return {
                results: [
                  { id: 'g1', metric: 'sessions', target: 500, current: 550, achieved_at: existingAchievedAt },
                ],
              };
            }
            return { results: [] };
          }),
          run: vi.fn(),
        })),
      })),
      batch: vi.fn((stmts) => stmts.map(() => ({ success: true }))),
    };

    await recalculateClassGoalProgress(mockDb, 'c1', 'org1', '2026-01-01', '2026-04-10', 'Spring 1 2025/26');
    expect(mockDb.batch).toHaveBeenCalledOnce();
    // Batch should still be called with update statements
    const batchCall = mockDb.batch.mock.calls[0][0];
    expect(batchCall).toHaveLength(1);
  });
});
